### ISSUE TITLE
undefined method for 'lock'

### ISSUE THREAD

**Issue by kilimchoi** [emq/sidekiq-lock#10]
Hi, 

I just added the gem and I'm getting, NameError: undefined local variable or method `lock'
I see the gem in the gemfile.lock list. 
I added the following to my worker 

```
include Sidekiq::Lock::Worker
sidekiq_options lock: { timeout: 1000, name: 'lock-worker' }
```

Any idea why it may not be working?

**Comment by peyterkim** [comment]
@kilimchoi did you figure this out? Running into the same issue.
