### ISSUE TITLE
Support inline locking too

### ISSUE THREAD

**Issue by jacquescrocker** [emq/sidekiq-lock#11]
I think Sidekiq lock should still allow workers to be run inline. Locking behavior should be the same

via `Worker.new.perform(args)`

As of right now `lock` is nil. 

I'm implementing this functionality now. Hopefully you wont mind it being merged back in

Thanks

**Comment by emq** [comment]
Hello @jacquescrocker 

Right now as you said it won't work as the lock method is defined using sidekiq's middleware; but I'm not sure what would be the real-life use-case here 🤔 can u plz elaborate?

**Comment by emaiax** [comment]
@jacquescrocker I believe you only need the middleware setup before testing your workers in inline mode.

```ruby
require "sidekiq/testing"
require "sidekiq/lock/testing/inline"
require "sidekiq/lock/middleware"

RSpec.configure do |config|
  config.before(:all) do
    Sidekiq::Testing.server_middleware do |chain|
      chain.add Sidekiq::Lock::Middleware
    end

    Sidekiq::Testing.inline!
  end
end
```

With this, your lock should work as expected.
https://github.com/mperham/sidekiq/wiki/Testing#testing-server-middleware

**Comment by emq** [comment]
Thx for feedback @emaiax <3

I suppose we can close this stale issue 😅
