### ISSUE TITLE
Is there a way to use n-locks?

### ISSUE THREAD

**Issue by sandric** [emq/sidekiq-lock#12]
I wonder if I can use multiple locks? The main reason - to be able to limit how many same job workers can go in parallel. So say I want to limit 1 job to be run concurrently with only 2 worker threads - can I somehow set 2 locks and then acquire first or second?

**Comment by emq** [comment]
Hey @sandric!

I'm not sure I understand exact use case, but it _seems_ this gem might not be a right solution for your problem - if you want to limit number of works per job (and by job I assume you mean _queue_ here?) you might simply spin-up multiple sidekiq processes and configure each process for each queue (consume only specific queue(s) per process and set number of threads for your needs) or maybe use something like ![sidekiq-limit_fetch](https://github.com/brainopia/sidekiq-limit_fetch)?

**Comment by sandric** [comment]
@emq Yeah, I tried `sidekiw-limit_fetch`, but for some reason my redis k8s pod just dies right after I start sidekiq worker :slightly_frowning_face: Yes, I could spawn other process just to run specific queue, but the thing is doing this I will load the same sidekiq + activerecord etc two times and I would like to avoid it. So I was thinking mb solution might be to use smth like mutex but instead of true/false check for acquisition - make it integer - and on acquire - check for limit and increment, while on release - decrement..

**Comment by emq** [comment]
I wouldn't worry about spinning multiple processes unless you're running your app under some heavy resources limits - but then again I would rethink using ruby in the first place.

If allocating some extra hardware resources solves your problem - I would say go for it; I'm almost sure it will be cheaper in the long-term than maintenance of some custom 'trickery' logic.

I'm gonna close this issue as it seems you have more of an architectural choice to make - and as usual _it depends_ ;) good luck!
