### ISSUE TITLE
Sidekiq lock not working

### ISSUE THREAD

**Issue by HienNguyenAsnet** [emq/sidekiq-lock#7]
I define a test job
```
class Job
  include Sidekiq::Worker
  include Sidekiq::Lock::Worker

  sidekiq_options queue: :test, retry: true, unique: :until_executing, lock: {
    timeout: 1.hour,
    name:    'index_lock',
    value:   proc { |klass, id, options= {}| "#{klass}:#{id}" }
  }

  def perform(klass, id, options = {})
    a = lock.acquire!
    puts a

    if a
      begin
        puts "process #{klass}, #{id}, #{options}"
        sleep 5.minutes
      ensure
        puts "release lock #{klass}:#{id}"
        lock.release!
      end
    else
      Job.perform_in 30.seconds, klass, id, options
    end
  ensure
    # GC.start
  end
end
```
Then I run
```
Job.perform_async 'a', 1
Job.perform_async 'a', 2
Job.perform_async 'a', 3
Job.perform_async 'a', 4
```

The log show
```
true
process a, 1, {}
true
process a, 1, {}
false
true
process a, 1, {}
true
process a, 1, {}
```

**Comment by emq** [comment]
HI @HienNguyenAsnet - can you tell me how exactly do you run it and what sidekiq version you're using?

**Comment by HienNguyenAsnet** [comment]
Hi @emq

Our code use sidekiq v4.1.2

**Comment by emq** [comment]
@HienNguyenAsnet I cannot reproduce this; copied & pasted your example, ran
```
sidekiq -q test -r ./job.rb -v -c 10
# then enqueued 4 jobs via console - irb -r ./job.rb
```
and lock is properly acquired; can you provide exact example how to reproduce your issue?

**Comment by HienNguyenAsnet** [comment]
I just config sidekiq in sidekiq.yml
```
:verbose: false
:concurrency: 10

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - default
  - test
```

Then run sidekiq process `bundle exec sidekiq`

Final I run rails console and perform job

**Comment by emq** [comment]
@HienNguyenAsnet for such lag in response, I just briefly checked it again after your latest comment and coudn't really reproduce it, I hope you finally resolved it tho

sidekiq-lock is now tested on all major sidekiq & rubies version on travis just in case; if you still having problems please provide more information (ruby version, sidekiq version, redis version, system/platform)
